# Generated by Django 2.0.4 on 2018-05-26 20:22

from django.db import migrations, models

def add_race_statuses(apps, schema_editor):
    '''
    Add race statuses
    '''
    RaceStatusModel = apps.get_model('races', 'RaceStatus')
    RaceStatusModel.objects.create(name='Queued')
    RaceStatusModel.objects.create(name='In Progress')
    RaceStatusModel.objects.create(name='Failed')
    RaceStatusModel.objects.create(name='Finished')


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0002_race_keyword'),
    ]

    operations = [
        migrations.CreateModel(
            name='RaceStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='race',
            name='status',
            field=models.ForeignKey(default=1, on_delete=models.deletion.CASCADE, to='races.RaceStatus'),
        ),
        migrations.RunPython(add_race_statuses),
    ]

