# Generated by Django 2.0.4 on 2018-05-26 20:22

from django.db import migrations

def add_race_statuses(apps, schema_editor):
    '''
    Add race statuses
    '''
    RaceStatusModel = apps.get_model('races', 'RaceStatus')
    RaceStatusModel.objects.create(name='Queued')
    RaceStatusModel.objects.create(name='In Progress')
    RaceStatusModel.objects.create(name='Failed')
    RaceStatusModel.objects.create(name='Finished')


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0003_auto_20180526_2022'),
    ]

    operations = [
        migrations.RunPython(add_race_statuses),
    ]

