# Generated by Django 2.0.4 on 2018-06-03 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0005_auto_20180603_1200'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(blank=True, max_length=255, null=True)),
                ('has_been_selected', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='KeywordType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='keyword',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='races.KeywordType'),
        ),
    ]
