# Generated by Django 2.0.4 on 2018-06-03 21:56

from django.db import migrations

def add_keyword_types(apps, schema_editor):
    '''
    Add keyword types
    '''
    KeywordTypeModel = apps.get_model('races', 'KeywordType')
    KeywordTypeModel.objects.create(name='Both')
    KeywordTypeModel.objects.create(name='Auto')
    KeywordTypeModel.objects.create(name='Manual')


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0006_auto_20180603_2154'),
    ]

    operations = [
        migrations.RunPython(add_keyword_types),
    ]
