# Generated by Django 2.0 on 2017-12-11 20:55

from django.db import migrations, models


def load_anonymous_agent(apps, schema_editor):
    Agent = apps.get_model("agents", "Agent")
    anonymous_agent = Agent(id=0, name='Anonymous')
    anonymous_agent.save()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(blank=True, max_length=255)),
            ],
        ),
        # migrations.RunPython(load_anonymous_agent)
    ]
