# Generated by Django 2.0 on 2018-01-07 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agents', '0002_auto_20171211_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='agents', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
