# Generated by Django 2.0 on 2018-04-16 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_agent_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
