# Generated by Django 2.0 on 2018-04-16 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_auto_20180416_1020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='email',
            new_name='gmail',
        ),
        migrations.RenameField(
            model_name='agent',
            old_name='password',
            new_name='gmail_password',
        ),
        migrations.RenameField(
            model_name='agent',
            old_name='name',
            new_name='title',
        ),
    ]
