# Generated by Django 2.0 on 2018-04-16 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0005_auto_20180416_1032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='title',
            new_name='name',
        ),
    ]
