# Generated by Django 2.0 on 2017-12-10 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snapshots', '0002_auto_20171210_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='snapshot',
            name='title',
            field=models.CharField(default='title', max_length=1000),
            preserve_default=False,
        ),
    ]
