# Generated by Django 2.0 on 2017-12-11 21:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_auto_20171211_2118'),
        ('snapshots', '0005_session'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='created_at',
            new_name='start',
        ),
        migrations.RemoveField(
            model_name='session',
            name='ended_at',
        ),
        migrations.RemoveField(
            model_name='session',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='session',
            name='agent_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='agents.Agent'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='end',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
