# Generated by Django 2.0 on 2017-12-11 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_auto_20171211_2118'),
        ('snapshots', '0006_auto_20171211_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='snapshot',
            name='agent_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='agents.Agent'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='snapshot',
            name='session_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='snapshots.Session'),
            preserve_default=False,
        ),
    ]
