# Generated by Django 2.0 on 2017-12-11 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snapshots', '0007_auto_20171211_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
