# Generated by Django 2.0 on 2017-12-11 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snapshots', '0008_auto_20171211_2147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='agent_id',
            new_name='agent',
        ),
        migrations.RenameField(
            model_name='snapshot',
            old_name='agent_id',
            new_name='agent',
        ),
        migrations.RenameField(
            model_name='snapshot',
            old_name='session_id',
            new_name='session',
        ),
    ]
