# Generated by Django 2.0 on 2018-02-08 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0002_auto_20180208_0728'),
        ('snapshots', '0012_session_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='snapshot',
            name='next_up_video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_up_video', to='youtube.Video'),
        ),
        migrations.AddField(
            model_name='snapshot',
            name='related_videos',
            field=models.ManyToManyField(to='youtube.Video'),
        ),
        migrations.AddField(
            model_name='snapshot',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video', to='youtube.Video'),
        ),
    ]
