# Generated by Django 2.0.4 on 2018-05-20 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snapshots', '0013_auto_20180208_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snapshot',
            name='image',
            field=models.ImageField(blank=True, max_length=254, null=True, upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='snapshot',
            name='source_code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
