# Generated by Django 2.0 on 2018-03-23 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('snapshots', '0013_auto_20180208_2142'),
        ('agents', '0003_agent_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agents.Agent')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snapshots.Session')),
            ],
        ),
        migrations.CreateModel(
            name='ScenarioStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ScenarioType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='scenario',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scenarios.ScenarioStatus'),
        ),
        migrations.AddField(
            model_name='scenario',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scenarios.ScenarioType'),
        ),
    ]
