# Generated by Django 2.0 on 2018-03-30 12:10

from django.db import migrations

def add_scenario_types(apps, schema_editor):
    '''
    Add task types
    '''
    TypeModel = apps.get_model('scenarios', 'ScenarioType')
    TypeModel.objects.create(name='Youtube Search')


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_scenario_types),
    ]
