# Generated by Django 2.0 on 2018-03-30 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0002_auto_20180330_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenarioconfig',
            name='scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='config', to='scenarios.Scenario'),
        ),
    ]
