# Generated by Django 2.0 on 2018-03-30 11:05

from django.db import migrations


def add_scenario_types(apps, schema_editor):
    '''
    Add scenario types
    '''
    TypeModel = apps.get_model('scenarios', 'ScenarioType')
    TypeModel.objects.create(name='Race')
    TypeModel.objects.create(name='Training')


def add_scenario_statuses(apps, schema_editor):
    '''
    Add scenario statuses
    '''
    StatusModel = apps.get_model('scenarios', 'ScenarioStatus')
    StatusModel.objects.create(name='Queued')
    StatusModel.objects.create(name='In Progress')
    StatusModel.objects.create(name='Failed')
    StatusModel.objects.create(name='Finished')


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0002_auto_20180323_0914'),
    ]

    operations = [
        migrations.RunPython(add_scenario_types),
        migrations.RunPython(add_scenario_statuses),
    ]
