# Generated by Django 2.0 on 2018-03-08 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('snapshots', '0013_auto_20180208_2142'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sentiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('sentiment', models.CharField(max_length=255)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snapshots.Snapshot')),
            ],
        ),
    ]
