# Generated by Django 2.0 on 2018-03-12 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentiment',
            name='watson_raw_tone',
            field=models.CharField(blank=True, max_length=10000),
        ),
    ]
