# Generated by Django 2.0 on 2018-03-12 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_sentiment_watson_raw_tone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentiment',
            name='sentiment',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
