# Generated by Django 2.0.4 on 2018-05-20 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_auto_20180323_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentiment',
            name='gcp_sentiment_magnitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='sentiment',
            name='gcp_sentiment_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='sentiment',
            name='snapshot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='snapshots.Snapshot'),
        ),
    ]
