# Generated by Django 2.0.4 on 2018-05-20 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_auto_20180520_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentiment',
            name='face_sentiment',
            field=models.TextField(blank=True, max_length=10009, null=True),
        ),
    ]
