# Generated by Django 2.0.4 on 2018-05-22 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0006_sentiment_face_sentiment'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentiment',
            name='caps_sentiment',
            field=models.FloatField(default=0.0),
        ),
    ]
