# Generated by Django 2.0.4 on 2018-05-22 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0007_sentiment_caps_sentiment'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentiment',
            name='punctuation_sentiment',
            field=models.FloatField(default=0.0),
        ),
    ]
