# Generated by Django 2.0.4 on 2018-05-23 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0008_sentiment_punctuation_sentiment'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentiment',
            name='gcp_comments_sentiment_magnitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='sentiment',
            name='gcp_comments_sentiment_score',
            field=models.FloatField(default=0.0),
        ),
    ]
