# Generated by Django 2.0.4 on 2018-05-29 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0009_auto_20180523_0556'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentiment',
            name='fakebox_raw',
            field=models.TextField(blank=True, max_length=10009, null=True),
        ),
        migrations.AddField(
            model_name='sentiment',
            name='fakebox_title_decision',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sentiment',
            name='fakebox_title_score',
            field=models.FloatField(default=0.0),
        ),
    ]
