# Generated by Django 2.0 on 2018-04-04 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0002_training_interval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingkeyword',
            name='training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='trainings.Training'),
        ),
    ]
