# Generated by Django 2.0 on 2018-03-30 11:41

from django.db import migrations


def add_task_types(apps, schema_editor):
    '''
    Add task types
    '''
    TypeModel = apps.get_model('tasks', 'TaskType')
    TypeModel.objects.create(name='Race')
    TypeModel.objects.create(name='Training')


def add_task_statuses(apps, schema_editor):
    '''
    Add task statuses
    '''
    StatusModel = apps.get_model('tasks', 'TaskStatus')
    StatusModel.objects.create(name='Queued')
    StatusModel.objects.create(name='In Progress')
    StatusModel.objects.create(name='Failed')
    StatusModel.objects.create(name='Finished')


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_task_types),
        migrations.RunPython(add_task_statuses),
    ]
