# Generated by Django 2.0 on 2018-03-30 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0002_auto_20180330_1210'),
        ('tasks', '0002_auto_20180330_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='scenario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scenarios.Scenario'),
        ),
    ]
