# Generated by Django 2.0 on 2018-03-20 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0002_auto_20180208_0728'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='description',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
    ]
