# Generated by Django 2.0.4 on 2018-05-20 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0004_video_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='meta',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
    ]
