# Generated by Django 2.0.4 on 2018-05-23 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0007_auto_20180523_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='comment_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
