# Generated by Django 2.0.4 on 2018-05-23 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0008_video_comment_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
